<?php
define('GREEN', 0);  
define('YELLOW', 1);    
define('RED', 2);

$matrix = [
    [GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN],
    [GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN],
    [GREEN, YELLOW, RED, RED, RED, RED, YELLOW, GREEN],
    [GREEN, YELLOW, RED, YELLOW, YELLOW, RED, YELLOW, GREEN],
    [GREEN, YELLOW, RED, YELLOW, YELLOW, RED, YELLOW, GREEN],
    [GREEN, YELLOW, RED, RED, RED, RED, YELLOW, GREEN],
    [GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN],
    [GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN],
];

 var_dump($matrix);