<table>
    <thead>
        <tr>
            <th>
                BB
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>        
            <td>
               aa
            </td>
        </tr>
    </tbody>
</table>